backend:
  # name: test-repo
  name: github
  repo: Gentostage/darya_blog
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://github.daryausova.website
display_url: https://daryausova.website
site_url: https://daryausova.website
logo_url: https://daryausova.website/favicon.png
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/post'
    path: "{{slug}}/index"
    preview_path: preview/{{slug}}
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      # - { label: 'Черновик', name: 'draft', widget: 'boolean', default: true }
      - { label: 'url', name: 'slug', widget: 'string' }
      - { label: 'Дата публикации', name: 'date', widget: 'datetime' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Тэги', name: 'tags', widget: 'list'}
      - { label: 'Категории', name: 'categories', widget: 'list' }
      - { label: "Фоновая картинка", name: "image", widget: "image" }
      - { label: 'Контент', name: 'body', widget: 'markdown' }

      