name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Copy to webserver
      if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) ||  github.event_name == 'push'
      run: rsync -v --delete -rvzh ./public/ www@87.249.50.16:/var/www/html/darya/
